services:
- mssql

init:
- appveyor version
- env
- cat /proc/meminfo
- sh: sudo sed  -i -e '/192.168.0.9/d' /etc/hosts
- cat /etc/hosts


test_script:
- sh: sleep 5
- sh: systemctl status mssql-server.service || true
- sh: cat /var/log/syslog | grep "$(date '+%b %d')"
- sh: sqlcmd -S localhost -U SA -P 'Password12!' -Q 'select @@VERSION'

build: off
