environment:
  APPVEYOR_SSH_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCUvrULRVnqephhFVqt2Gm+MRkLewIa7bfrrHTp1+Y6ulBlycVumHKsLMzeulCnxUP7+gVJ9cIQtbNBOt9oGEcSGBNGtmoDPsNOo6lA/9eVkQQR+WlgKYFK2LgtJY2FMpmkeD8BA06lz0arR6oQAac6Yjfn7HQq0XRkmJaFwrgc258JwSldbp9RNGDd7j6DzF1F3QsiLRFeHqZni6eNMnC3Xhmh0Jj4hDjYpeXWKuZjGPXAuVry0XTXPoLaUNfi0R9aDhtD8NszdzWKNwYt2iPKBVaSkMeDFkyLo3+CGLHKw//Uw8GIhtRQk4S6/Yfo7LS3leOJxJs7dryJiUS0IwT9 wasapl@appveyor.com
  APPVEYOR_SSH_BLOCK: true
  
services:
- mssql

init:
- ps: Update-AppveyorBuild -Message "Image '$env:APPVEYOR_BUILD_WORKER_IMAGE'@'$env:APPVEYOR_BUILD_WORKER_CLOUD' cloud. $env:APPVEYOR_REPO_COMMIT_MESSAGE"
- appveyor version
- sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
- sh: echo $APPVEYOR_BUILD_WORKER_CLOUD
- sh: awk '/MemTotal/{printf "%s %d MB", $1, $2 / 1024;}' < /proc/meminfo; 
- sh: sudo apt install stress
#- sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
- sh: |
    function getmem() { 
      awk '/MemTotal/{printf "%d", $2 / 1024;}' < /proc/meminfo; 
    }
    function stressmem() {
      local MEGS=$1
      echo stress $MEGS megabytes
      stress --vm-bytes ${MEGS}M --vm-keep --timeout 10s -m 5
    }
    OLD_SWAPPINESS=$(sudo sysctl vm.swappiness|tr -d " " )
    sudo sysctl -w vm.swappiness=10
    MEM_TOTAL_0=$( getmem )
    stress_counter=1
    while [ $(getmem) -le 2000 ] && [ $stress_counter -le 5 ]; do
      grep Mem /proc/meminfo
      MEGS=$(awk '/MemAvailable/{printf "%d\n", $2 * 1.1 / 1024;}' < /proc/meminfo)
      stressmem $MEGS
      ((stress_counter++))
    done
    sudo sysctl -w $OLD_SWAPPINESS
- sh: sleep 8
- free

test_script:
- sh: systemctl status mssql-server.service || true
- sh: |
    echo "Waiting for server to boot up..."
    attempts=0
    max_attempts=30
    while ( ! sudo lsof -i -P -n | grep  :1433 >/dev/null || ! sudo lsof -i -P -n | grep  :1434 > /dev/null )  && [[ $attempts -le $max_attempts ]] ; do
        attempts=$((attempts+1))
        sleep 1;
        echo "waiting... (${attempts}/${max_attempts})"
    done

- sh: sudo grep "$(date '+%b %e')" /var/log/syslog > syslog.log
- sh: sudo grep "$(date '+%Y-%m-%d')" /var/opt/mssql/log/errorlog > error.log
- sh: sqlcmd -S localhost -U SA -P 'Password12!' -Q 'select @@VERSION'


build: off

on_failure:
- appveyor PushArtifact syslog.log
- appveyor PushArtifact error.log
