services:
- mssql

init:
- appveyor version
- sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
- sh: echo $APPVEYOR_BUILD_WORKER_CLOUD
- env
- cat /proc/meminfo
- sh: sudo sed  -i -e '/192.168.0.9/d' /etc/hosts
- cat /etc/hosts


test_script:
- sh: systemctl status mssql-server.service --no-pager || true
- sh: grep "$(date '+%b %d')" /var/log/syslog > syslog.log
- sh: ls -l syslog.log
- sh: sqlcmd -S localhost -U SA -P 'Password12!' -Q 'select @@VERSION'

build: off

artifacts:
  - path: syslog.log
    name: syslog

on_failure:
- appveyor PushArtifact syslog.log
