environment:
  APPVEYOR_SSH_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCUvrULRVnqephhFVqt2Gm+MRkLewIa7bfrrHTp1+Y6ulBlycVumHKsLMzeulCnxUP7+gVJ9cIQtbNBOt9oGEcSGBNGtmoDPsNOo6lA/9eVkQQR+WlgKYFK2LgtJY2FMpmkeD8BA06lz0arR6oQAac6Yjfn7HQq0XRkmJaFwrgc258JwSldbp9RNGDd7j6DzF1F3QsiLRFeHqZni6eNMnC3Xhmh0Jj4hDjYpeXWKuZjGPXAuVry0XTXPoLaUNfi0R9aDhtD8NszdzWKNwYt2iPKBVaSkMeDFkyLo3+CGLHKw//Uw8GIhtRQk4S6/Yfo7LS3leOJxJs7dryJiUS0IwT9 wasapl@appveyor.com
  APPVEYOR_SSH_BLOCK: true
  
services:
- mssql

init:
- appveyor version
- sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
- sh: echo $APPVEYOR_BUILD_WORKER_CLOUD
- env
- sh: sudo apt install stress
- sh: stress --vm-bytes 1500M --timeout 10s -m 1 &
- sh: sleep 8
#- cat /proc/meminfo
- top
- sh: sudo sed  -i -e '/192.168.0.9/d' /etc/hosts
- cat /etc/hosts


test_script:
- sh: sleep 5
- sh: systemctl status mssql-server.service || true
- sh: grep "$(date '+%b %d')" /var/log/syslog > syslog.log
- sh: ls -l syslog.log
#- sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
- sh: read -r IP_NUM IP_DEV IP_FAM IP_ADDR IP_REST <<< "$(ip -o -4 addr show up primary scope global)"
- sh: echo ${IP_ADDR%/*}
- sh: sudo bash -c "echo 127.0.1.1  $HOSTNAME >> /etc/hosts"
- sh: cat /etc/hosts
- sh: sqlcmd -S localhost -U SA -P 'Password12!' -Q 'select @@VERSION'
#- sh: journalctl --no-pager -u appveyor-build-agent.service


build: off

#artifacts:
#  - path: syslog.log
#    name: syslog

on_failure:
- appveyor PushArtifact syslog.log
