services:
- mssql

init:
- appveyor version
- env
- cat /proc/meminfo
- cat /etc/hosts
- sh: systemctl status mssql-server.service

test_script:
- sh: sleep 5
- sh: sqlcmd -S localhost -U SA -P 'Password12!' -Q 'select @@VERSION'

build: off
