environment:
  APPVEYOR_SSH_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCUvrULRVnqephhFVqt2Gm+MRkLewIa7bfrrHTp1+Y6ulBlycVumHKsLMzeulCnxUP7+gVJ9cIQtbNBOt9oGEcSGBNGtmoDPsNOo6lA/9eVkQQR+WlgKYFK2LgtJY2FMpmkeD8BA06lz0arR6oQAac6Yjfn7HQq0XRkmJaFwrgc258JwSldbp9RNGDd7j6DzF1F3QsiLRFeHqZni6eNMnC3Xhmh0Jj4hDjYpeXWKuZjGPXAuVry0XTXPoLaUNfi0R9aDhtD8NszdzWKNwYt2iPKBVaSkMeDFkyLo3+CGLHKw//Uw8GIhtRQk4S6/Yfo7LS3leOJxJs7dryJiUS0IwT9 wasapl@appveyor.com
  APPVEYOR_SSH_BLOCK: true
  
services:
- mssql

init:
- appveyor version
- sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
- sh: echo $APPVEYOR_BUILD_WORKER_CLOUD
- sh: sudo apt install stress
- sh: stress --vm-bytes 1500M --timeout 10s -m 1 &
- sh: sleep 8
- free
#- sh: sudo sed  -i -e '/192.168.0.9/d' /etc/hosts
- cat /etc/hosts

test_script:
- sh: systemctl status mssql-server.service || true
- sh: grep "$(date '+%b %d')" /var/log/syslog > syslog.log
- sh: sqlcmd -S localhost -U SA -P 'Password12!' -Q 'select @@VERSION'


build: off

#artifacts:
#  - path: syslog.log
#    name: syslog

on_failure:
- appveyor PushArtifact syslog.log
